language: go

matrix:
  include:
  - go: 1.x
    os: linux
    env: FULL=true
  - go: 1.x
    os: osx
  - go: tip
    os: linux

install:
  - if [ "$FULL" = "true" ]; then go get github.com/golang/lint/golint; fi;
  - if [ "$FULL" = "true" ]; then go get github.com/mattn/goveralls; fi;

before_script:
  - if [ "$FULL" = "true" ]; then go vet $(go list ./... | grep -v vendor); fi;
  - if [ "$FULL" = "true" ]; then test -z "$(gofmt -s -l . 2>&1 | grep -v vendor | tee /dev/stderr)"; fi;
  - if [ "$FULL" = "true" ]; then go list ./... | grep -v /vendor/ | xargs -L1 golint; fi;

script:
  - if [ "$FULL" = "true" ]; then goveralls -service=travis-ci; else go test $(go list ./... | grep -v /vendor/); fi;
