language: go

go:
  - 1.x
  - master

os:
  - linux
  - osx

before_install:
  - go get github.com/golang/lint/golint
  - go get github.com/mattn/goveralls

install:
  - echo "This is an override of the default install deps step in travis."

before_script:
  - go vet $(go list ./... | grep -v vendor)
  - test -z "$(gofmt -s -l . 2>&1 | grep -v vendor | tee /dev/stderr)"
  - go list ./... | grep -v /vendor/ | xargs -L1 golint

script:
  - goveralls -service=travis-ci
