# Compose file used for the integration test suite
version: '3'

services:

  consul:
    image: consul 
    command: agent -server -bind=127.0.0.1 -client=0.0.0.0
    ports:
      - "8400:8400"
      - "8500:8500/tcp"
      - "8600:53/udp"
    environment:  
      - CONSUL_LOCAL_CONFIG={"acl_datacenter":"dc1","acl_default_policy":"deny","acl_down_policy":"extend-cache","acl_master_token":"the_one_ring","bootstrap_expect":1,"datacenter":"dc1","data_dir":"/usr/local/bin/consul.d/data","server":true}
